version: "3.9"
networks:
  infra_my_net:
    external: true
services:
  jump:
    image: jdxj/jump:0.1.0
    command: [/jump/jump.out, -confdir, /jump/conf]
    restart: unless-stopped
    networks:
      infra_my_net:
        ipv4_address: ${JUMP_IP}
    volumes:
      - type: bind
        source: ${CONF_PATH}
        target: /jump/conf
        read_only: true
      - type: bind
        source: ${JUMP_LOGS_PATH}
        target: /jump/logs
        read_only: false
