version: "3.9"

networks:
  infra_my_net:
    external: true

services:
  my_miniflux:
    image: miniflux/miniflux:latest
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_IP}:5432/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${FEED_USER}
      - ADMIN_PASSWORD=${FEED_PASS}
    restart: unless-stopped
    networks:
      infra_my_net:
        ipv4_address: ${FEED_IP}
